[workspace]
# a lot of changes going into 4.0.0; ignoring breaking changes for now
semver_check = false

[[package]]
name = "fiddler"
version_group = "fiddler"

[[package]]
name = "fiddler-cli"
version_group = "fiddler"

[[package]]
name = "fiddler-script"
version_group = "script"
