[package]
name = "fiddler-script"
version = "0.1.0"
edition = "2021"
description = "A minimal C-style scripting language interpreter"
license-file = "../LICENSE"
readme = "README.md"

[dependencies]
thiserror = "2"
serde_json = "1"
flate2 = "1"
base64 = "0.22"

[dev-dependencies]
